# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in /usr/local/Cellar/android-sdk/24.3.3/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# react-native-reanimated
-keep class com.swmansion.reanimated.** { *; }
-keep class com.facebook.react.turbomodule.** { *; }

# Add any project specific keep options here:


# ---------------------------------------------------------------------------
# Veil release rules. Generated by plugins/withProguardRules.js.
# ---------------------------------------------------------------------------

# React Native and Hermes reach these from JS by name.
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.jni.** { *; }
-keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class * { @com.facebook.react.bridge.ReactMethod <methods>; }
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keepclassmembers class * { @com.facebook.proguard.annotations.DoNotStrip *; }

# Expo modules are resolved reflectively through the modules registry.
-keep class expo.modules.** { *; }
-keepclassmembers class * { @expo.modules.core.interfaces.ExpoMethod <methods>; }

# WebRTC. The peer connection and its observers are invoked from native code,
# so renaming them breaks call setup in ways that only appear at runtime.
-keep class org.webrtc.** { *; }
-keep class com.oney.WebRTCModule.** { *; }
-dontwarn org.webrtc.**

# SQLite bindings used by expo-sqlite.
-keep class io.requery.android.database.** { *; }
-dontwarn io.requery.**

# Keep annotations and generic signatures. Stripping these breaks reflective
# lookups and produces failures far from their cause.
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod

# Strip logging from release builds. Nothing in this app should log message
# content, but removing the calls entirely means a stray debug log added later
# cannot leak into logcat, which any app with READ_LOGS could read on older
# Android versions.
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
}
