/**
 * Voice call keys and the short authentication string.
 *
 * How a Veil call is secured, and why it is layered this way:
 *
 * 1. Call setup travels as ordinary encrypted messages over the Double
 *    Ratchet. So the offer/answer and the media root secret are already
 *    end-to-end encrypted and authenticated by identity keys before any media
 *    flows. There is no separate, weaker call-signalling trust path — which is
 *    the usual weak point in "encrypted calling".
 *
 * 2. Media is protected by SFrame (see sframe.ts) using keys derived here.
 *    This is *inside* WebRTC's own DTLS-SRTP. The reason for both: DTLS-SRTP
 *    terminates at whatever relays the media, so a TURN server or SFU sees
 *    plaintext media. SFrame keys never leave the two endpoints, so a relay
 *    carries ciphertext it cannot open. For a 1:1 call that means the operator
 *    can route the call without being able to listen to it.
 *
 * 3. The SAS lets the two people detect an active MITM by speaking four words
 *    to each other. It is the audible equivalent of a safety number, and it is
 *    bound to the negotiated media secret, so it only matches if both ends
 *    derived the same keys.
 */

import { SHARED_SECRET_LEN, kdf, random, wipe } from './primitives.js';
import { LABELS } from './kdf.js';
import { MalformedInputError } from './errors.js';
import { Writer, concat, utf8 } from './wire.js';
import { type PublicIdentity } from './identity.js';

/** Role in the call. Fixes the ordering of transcript inputs on both ends. */
export type CallRole = 'caller' | 'callee';

export interface CallSecrets {
  /** Root secret for this call; sent inside a ratchet-encrypted setup message. */
  readonly mediaRootSecret: Uint8Array;
}

/** Fresh per-call media secret. Generated by the caller, sent E2EE to the callee. */
export function createCallSecrets(): CallSecrets {
  return { mediaRootSecret: random(SHARED_SECRET_LEN) };
}

/**
 * Transcript binding the call to both identities and both DTLS fingerprints.
 *
 * Including the DTLS certificate fingerprints is what ties the SFrame layer to
 * the actual transport session. Without that, an attacker who relayed the media
 * could pair our SFrame keys with its own DTLS session; with it, the SAS the
 * users compare would differ and the substitution is detectable.
 */
function callTranscript(params: {
  callerIdentity: PublicIdentity;
  calleeIdentity: PublicIdentity;
  callId: Uint8Array;
  callerDtlsFingerprint: Uint8Array;
  calleeDtlsFingerprint: Uint8Array;
}): Uint8Array {
  return new Writer()
    .fixed(utf8.encode('Veil/v1/Call'))
    .bytes(params.callId)
    .bytes(params.callerIdentity.signingPublicKey)
    .bytes(params.calleeIdentity.signingPublicKey)
    .bytes(params.callerDtlsFingerprint)
    .bytes(params.calleeDtlsFingerprint)
    .finish();
}

export interface CallKeyMaterial {
  /** Key we encrypt our outgoing media frames with. */
  readonly sendKey: Uint8Array;
  /** Key we decrypt the peer's frames with. */
  readonly receiveKey: Uint8Array;
  /** Four words both users read aloud to rule out an active MITM. */
  readonly sas: string;
  /** Numeric form, for users who prefer digits or for accessibility tooling. */
  readonly sasDigits: string;
}

/**
 * Derive directional media keys plus the SAS.
 *
 * Send and receive keys are separate and role-derived, so the two directions
 * never share a keystream — reusing one key for both would be a nonce-reuse
 * catastrophe with a stream cipher.
 */
export function deriveCallKeys(params: {
  secrets: CallSecrets;
  role: CallRole;
  callerIdentity: PublicIdentity;
  calleeIdentity: PublicIdentity;
  callId: Uint8Array;
  callerDtlsFingerprint: Uint8Array;
  calleeDtlsFingerprint: Uint8Array;
}): CallKeyMaterial {
  const transcript = callTranscript(params);

  const callerKey = kdf(
    params.secrets.mediaRootSecret,
    transcript,
    concat(LABELS.sframeSender, utf8.encode('/caller')),
    SHARED_SECRET_LEN,
  );
  const calleeKey = kdf(
    params.secrets.mediaRootSecret,
    transcript,
    concat(LABELS.sframeSender, utf8.encode('/callee')),
    SHARED_SECRET_LEN,
  );

  const sasBytes = kdf(params.secrets.mediaRootSecret, transcript, LABELS.callSas, 8);
  const sas = sasWords(sasBytes);
  const sasDigits = sasNumeric(sasBytes);
  wipe(sasBytes, transcript);

  if (params.role === 'caller') {
    return { sendKey: callerKey, receiveKey: calleeKey, sas, sasDigits };
  }
  return { sendKey: calleeKey, receiveKey: callerKey, sas, sasDigits };
}

/**
 * PGP-style word list.
 *
 * 256 short, phonetically distinct English words, so one byte maps to exactly
 * one word with no bias. Words were chosen to be hard to confuse when spoken
 * over a low-bitrate voice codec, which is the channel they must survive.
 */
export const SAS_WORDS: readonly string[] = [
  'absurd', 'acme', 'adrift', 'adult', 'afflict', 'ahead', 'aimless', 'algol',
  'allow', 'alone', 'ammo', 'ancient', 'apple', 'artist', 'assume', 'athens',
  'atlas', 'aztec', 'baboon', 'backfield', 'backward', 'banjo', 'beaming', 'bedlamp',
  'beehive', 'beeswax', 'befriend', 'belfast', 'berserk', 'billiard', 'bison', 'blackjack',
  'blockade', 'blowtorch', 'bluebird', 'bombast', 'bookshelf', 'brackish', 'breadline', 'breakup',
  'brickyard', 'briefcase', 'burbank', 'button', 'buzzard', 'cement', 'chairlift', 'chatter',
  'checkup', 'chisel', 'choking', 'chopper', 'christmas', 'clamshell', 'classic', 'classroom',
  'cleanup', 'clockwork', 'cobra', 'commence', 'concert', 'cowbell', 'crackdown', 'cranky',
  'crowfoot', 'crucial', 'crumpled', 'crusade', 'cubic', 'dashboard', 'deadbolt', 'deckhand',
  'dogsled', 'dragnet', 'drainage', 'dreadful', 'drifter', 'dropper', 'drumbeat', 'drunken',
  'dupont', 'dwelling', 'eating', 'edict', 'egghead', 'eightball', 'endorse', 'endow',
  'enlist', 'erase', 'escape', 'exceed', 'eyeglass', 'eyetooth', 'facial', 'fallout',
  'flagpole', 'flatfoot', 'flytrap', 'fracture', 'framework', 'freedom', 'frighten', 'gazelle',
  'geiger', 'glitter', 'glucose', 'goggles', 'goldfish', 'gremlin', 'guidance', 'hamlet',
  'highchair', 'hockey', 'indoors', 'indulge', 'inverse', 'involve', 'island', 'jawbone',
  'keyboard', 'kickoff', 'kiwi', 'klaxon', 'locale', 'lockup', 'merit', 'minnow',
  'miser', 'mohawk', 'mural', 'music', 'necklace', 'neptune', 'newborn', 'nightbird',
  'oakland', 'obtuse', 'offload', 'optic', 'orca', 'payday', 'peachy', 'pheasant',
  'physique', 'playhouse', 'pluto', 'preclude', 'prefer', 'preshrunk', 'printer', 'prowler',
  'pupil', 'puppy', 'python', 'quadrant', 'quiver', 'quota', 'ragtime', 'ratchet',
  'rebirth', 'reform', 'regain', 'reindeer', 'rematch', 'repay', 'retouch', 'revenge',
  'reward', 'rhythm', 'ribcage', 'ringbolt', 'robust', 'rocker', 'ruffled', 'sailboat',
  'sawdust', 'scallion', 'scenic', 'scorecard', 'scotland', 'seabird', 'select', 'sentence',
  'shadow', 'shamrock', 'showgirl', 'skullcap', 'skydive', 'slingshot', 'slowdown', 'snapline',
  'snapshot', 'snowcap', 'snowslide', 'solo', 'southward', 'soybean', 'spaniel', 'spearhead',
  'spellbind', 'spheroid', 'spigot', 'spindle', 'spyglass', 'stagehand', 'stagnate', 'stairway',
  'standard', 'stapler', 'steamship', 'sterling', 'stockman', 'stopwatch', 'stormy', 'sugar',
  'surmount', 'suspense', 'sweatband', 'swelter', 'tactics', 'talon', 'tapeworm', 'tempest',
  'tiger', 'tissue', 'tonic', 'topmost', 'tracker', 'transit', 'trauma', 'treadmill',
  'trojan', 'trouble', 'tumor', 'tunnel', 'tycoon', 'uncut', 'unearth', 'unwind',
  'uproot', 'upset', 'upshot', 'vapor', 'village', 'virus', 'vulcan', 'waffle',
  'wallet', 'watchword', 'wayside', 'willow', 'woodlark', 'zulu', 'alpine', 'bravado',
];

/** First four bytes -> four words. ~32 bits of MITM detection, read aloud in seconds. */
export function sasWords(bytes: Uint8Array): string {
  if (bytes.length < 4) {
    throw new MalformedInputError('SAS needs at least 4 bytes');
  }
  if (SAS_WORDS.length !== 256) {
    throw new MalformedInputError(`SAS word list must have exactly 256 entries, has ${SAS_WORDS.length}`);
  }
  return [0, 1, 2, 3].map((i) => SAS_WORDS[bytes[i]!]!).join(' ');
}

/** Numeric SAS: six digits from the same bytes. */
export function sasNumeric(bytes: Uint8Array): string {
  if (bytes.length < 4) {
    throw new MalformedInputError('SAS needs at least 4 bytes');
  }
  let value = 0;
  for (let i = 0; i < 4; i++) value = value * 256 + bytes[i]!;
  return (value % 1_000_000).toString().padStart(6, '0');
}
