/**
 * ProGuard/R8 keep rules.
 *
 * R8 is enabled for release builds because stripping debug metadata and
 * renaming classes raises the cost of reverse-engineering the client. The
 * trade is that R8 removes code it cannot see being used, and React Native,
 * Expo modules and WebRTC all reach their native classes by *reflection* from
 * JavaScript - which R8 cannot follow. Without keep rules, a release build
 * compiles cleanly and then crashes at runtime on a missing class.
 *
 * These rules are conservative on purpose: a slightly larger APK is a much
 * better outcome than a release that fails only in the field.
 *
 * Written by a plugin rather than edited in place so `expo prebuild` cannot
 * discard it.
 */

const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

const RULES = `
# ---------------------------------------------------------------------------
# Veil release rules. Generated by plugins/withProguardRules.js.
# ---------------------------------------------------------------------------

# React Native and Hermes reach these from JS by name.
-keep class com.facebook.react.** { *; }
-keep class com.facebook.hermes.** { *; }
-keep class com.facebook.jni.** { *; }
-keepclassmembers class * { @com.facebook.react.uimanager.annotations.ReactProp <methods>; }
-keepclassmembers class * { @com.facebook.react.bridge.ReactMethod <methods>; }
-keep @com.facebook.proguard.annotations.DoNotStrip class *
-keepclassmembers class * { @com.facebook.proguard.annotations.DoNotStrip *; }

# Expo modules are resolved reflectively through the modules registry.
-keep class expo.modules.** { *; }
-keepclassmembers class * { @expo.modules.core.interfaces.ExpoMethod <methods>; }

# WebRTC. The peer connection and its observers are invoked from native code,
# so renaming them breaks call setup in ways that only appear at runtime.
-keep class org.webrtc.** { *; }
-keep class com.oney.WebRTCModule.** { *; }
-dontwarn org.webrtc.**

# SQLite bindings used by expo-sqlite.
-keep class io.requery.android.database.** { *; }
-dontwarn io.requery.**

# Keep annotations and generic signatures. Stripping these breaks reflective
# lookups and produces failures far from their cause.
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod

# Strip logging from release builds. Nothing in this app should log message
# content, but removing the calls entirely means a stray debug log added later
# cannot leak into logcat, which any app with READ_LOGS could read on older
# Android versions.
-assumenosideeffects class android.util.Log {
    public static *** d(...);
    public static *** v(...);
    public static *** i(...);
}
`;

module.exports = function withProguardRules(config) {
  return withDangerousMod(config, [
    'android',
    (mod) => {
      const rulesPath = path.join(
        mod.modRequest.platformProjectRoot,
        'app',
        'proguard-rules.pro',
      );
      const existing = fs.existsSync(rulesPath) ? fs.readFileSync(rulesPath, 'utf8') : '';
      if (!existing.includes('Generated by plugins/withProguardRules.js')) {
        fs.writeFileSync(rulesPath, `${existing}\n${RULES}`);
      }
      return mod;
    },
  ]);
};
